name: CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check with isort
        run: isort . --check-only

      - name: Check with black
        run: black --check .

      - name: Check with flake8
        run: flake8 . --max-line-length=88 --extend-ignore=E402,D100,D401

    #   - name: Run unit tests
    #     run: |
    #       python --version
    #       pytest tests/ --ignore=tests/test_chat_provider.py 